apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file ../smart-home-app/docker-compose.yml convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: monolith
  name: monolith
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: monolith
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file ../smart-home-app/docker-compose.yml convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: monolith
    spec:
      containers:
        - env:
            - name: DB_HOST
            - name: DB_NAME
            - name: DB_PASSWORD
            - name: DB_PORT
            - name: DB_URL
              value: jdbc:postgresql://:@:/
            - name: DB_USER
          image: dmitrys80/smart-home-monolith:1.0
          name: monolith
          ports:
            - containerPort: 8081
              protocol: TCP
      restartPolicy: Always
