apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file ../smart-home-app/docker-compose.yml convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: monolith
  name: monolith
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    io.kompose.service: monolith
