apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file ../smart-home-app/docker-compose.yml convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: telemetry
  name: telemetry
spec:
  type: NodePort
  ports:
    - name: "3001"
      port: 3001
      targetPort: 3001
  selector:
    io.kompose.service: telemetry
