apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file ../smart-home-app/docker-compose.yml convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: telemetry
  name: telemetry
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: telemetry
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file ../smart-home-app/docker-compose.yml convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: telemetry
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: db-server
            - name: DB_NAME
              value: telemetry_db
            - name: DB_PASSWORD
              value: admin
            - name: DB_PORT
              value: '5432'
            - name: DB_USER
              value: admin
          image: dmitrys80/smart-home-telemetry:1.0
          name: telemetry
          ports:
            - containerPort: 3001
              protocol: TCP
      restartPolicy: Always
