@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

HIDE_STEREOTYPE()
SHOW_PERSON_PORTRAIT()

Person(engineer, "Engineer", "Устанавливает систему отопления в доме клиента")
Person(user, "User", "Управляет температурой в доме")

System_Boundary(smartHomeSystem, "Smart Home"){
    Container(smartHomeWeb, "Web Client", "outsource", \
        $descr="Предоставляет пользовательский интерфейс для управления")
    Container(smartHomeServer, "Smart Home Server", "Java 17, SpringBoot", \
        $descr="Введет учет клиентских систем отопления. Управляет температурой в домах клиентов")
    ContainerDb(smartHomeDb, "Database", "PostgreSQL", \
        $descr="Хранит данные")
}

System_Ext(smartHomeDevice,\
    "Heating System",\
    "Мониторит температуру в доме. Обогревает дом",\
    $sprite="robot",\
    $type="Hardware System")

Rel(user, smartHomeWeb, "Устанавливает температуру в доме", "HTTP/REST")
Rel(user, smartHomeWeb, "Проверяет температуру в доме", "HTTP/REST")

Rel_L(smartHomeWeb, smartHomeServer, "Использует", "HTTP/REST")
Rel_L(smartHomeServer, smartHomeDb, "Использует", "JDBC")

Rel(engineer, smartHomeServer, "Добавляет данные системы отопления", "manual query")
Rel(smartHomeServer, smartHomeDevice, "Включает/выключает систему отопления", "standard protocol")
Rel(smartHomeServer, smartHomeDevice, "Запрашивает температуру в доме", "standard protocol")
@enduml